name: "Dev deployment"

# Ensure that only a single job or workflow using the same concurrency group
# runs at a time.
concurrency: 1

# Trigger this workflow whenever a pull request is pushed to the repo's
# main branch.
on:
  push:
    branches:
      - main

jobs:
  test:
    name: "Run unit tests"
    runs-on: ubuntu-latest

    steps:
      # Check out this repo, so that this workflow can access it.
      - uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the Python version here

      # Install testing dependencies
      - name: Install test dependencies
        working-directory: ./project
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}  # Pass the secret token here
        run: |
          python -m unittest ./project/src/unit-test.py
    
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    needs: test  

    steps:
      # Check out this repo, so that this workflow can access it.
      - uses: actions/checkout@v3

      # Set up Python environment for deployment
      - name: Set up Python for deployment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Download the Databricks CLI
      - uses: databricks/setup-cli@main

      # Deploy the bundle to the "prod" target as defined
      # in the bundle's settings file.
      - run: databricks bundle deploy
        working-directory: ./project
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
