name: "Dev deployment"

concurrency: 1

on:
  push:
    branches:
      - main

jobs:
  test:
    name: "Run unit tests"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install test dependencies
        working-directory: ./project
        run: |
          pip install -r requirements.txt

      #  Install Java & Spark 
      # Install Java & Spark
      - name: Install Java & Spark
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk  # Install Java 11
          wget https://dlcdn.apache.org/spark/spark-3.4.1/spark-3.4.1-bin-hadoop3.2.tgz  # Make sure the URL is correct
          tar -xvzf spark-3.4.1-bin-hadoop3.2.tgz
          sudo mv spark-3.4.1-bin-hadoop3.2 /opt/spark
          echo "export SPARK_HOME=/opt/spark" >> ~/.bashrc
          echo "export PATH=\$SPARK_HOME/bin:\$PATH" >> ~/.bashrc
          echo "export PYSPARK_PYTHON=python3" >> ~/.bashrc
          source ~/.bashrc


      #  Install PySpark
      - name: Install PySpark
        run: pip install pyspark

      # Run Unit Tests
      - name: Run unit tests
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          python -m unittest ./project/tests/unit-test.py
          python -m unittest ./project/tests/test_schema_validation.py
    
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    needs: test  

    steps:
      # Check out this repo, so that this workflow can access it.
      - uses: actions/checkout@v3

      # Set up Python environment for deployment
      - name: Set up Python for deployment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Download the Databricks CLI
      - uses: databricks/setup-cli@main

      # Deploy the bundle to the "prod" target as defined
      # in the bundle's settings file.
      - run: databricks bundle deploy
        working-directory: ./project
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
