name: "Dev deployment"

concurrency: 1

on:
  push:
    branches:
      - main

jobs:
  test:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    env:
      USE_LOCAL_SPARK: "true"
      DATABRICKS_HOST: "https://adb-1803686465879368.8.azuredatabricks.net/"
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install test dependencies
        working-directory: ./project
        run: |
          pip install -r requirements.txt

      # Uninstall Databricks Connect to avoid conflicts
      - name: Uninstall Databricks Connect
        if: env.USE_LOCAL_SPARK == 'true'
        run: pip uninstall -y databricks-connect
        
      # Run Unit Tests
      - name: Run unit tests
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          python -m unittest ./project/tests/unit-test.py
          python -m unittest ./project/tests/test_schema_validation.py
    
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    needs: test  

    steps:
      # Check out this repo, so that this workflow can access it.
      - uses: actions/checkout@v3

      # Set up Python environment for deployment
      - name: Set up Python for deployment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Download the Databricks CLI
      - uses: databricks/setup-cli@main

      # Deploy the bundle to the "prod" target as defined
      # in the bundle's settings file.
      - run: databricks bundle deploy
        working-directory: ./project
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
